# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_qDnZOBpyI-R1n7nguT1IehiUP6K6Ph
"""

import streamlit as st
import math
import pandas as pd

st.set_page_config(page_title="스티커 견적 계산기", page_icon="📐", layout="centered")

def format_number(n): return format(n, ",").replace(",", ".")
def number_to_korean(num):
    digits = ["", "일", "이", "삼", "사", "오", "육", "칠", "팔", "구"]
    units = ["", "십", "백", "천"]
    big_units = ["", "만", "억", "조", "경"]
    result, group = "", 0
    while num > 0:
        part, part_str = num % 10000, ""
        num //= 10000
        for i in range(4):
            d = part % 10
            part //= 10
            if d != 0:
                part_str = (units[i] if d == 1 and i > 0 else digits[d] + units[i]) + part_str
        result = part_str + big_units[group] + result if part_str else result
        group += 1
    return result

def format_result(n): return f"{format_number(n)} ({number_to_korean(n)})"

st.markdown("<h1 style='text-align:center; color:#00b894;'>🧾 스티커 견적 계산기</h1>", unsafe_allow_html=True)

tab1, tab2, tab3 = st.tabs(["📐 면적 계산기", "📦 헤다포장", "🎨 기타 견적"])

# ---------------- TAB 1: 면적 계산기 ----------------
with tab1:
    st.markdown("### 📐 면적 계산기 (업그레이드)")
    col1_area, col2_area, col3_area = st.columns(3)
    with col1_area:
        width = st.number_input("가로(mm)", min_value=1.0, value=50.0, step=1.0)
    with col2_area:
        height = st.number_input("세로(mm)", min_value=1.0, value=50.0, step=1.0)
    with col3_area:
        quantity = st.number_input("총 수량", min_value=1, value=100, step=1)

    sheet_type = st.selectbox("기본 용지 사이즈", ["270x400mm", "280x400mm"])

    if st.button("면적 계산", key="area_calc_btn"):
        max_width, max_height = (270, 400) if sheet_type == "270x400mm" else (280, 400)
        num_width = math.floor(max_width / width)
        num_height = math.floor(max_height / height)
        total_per_sheet = num_width * num_height

        if total_per_sheet == 0:
            st.error("❌ 해당 크기는 용지에 들어가지 않습니다.")
        else:
            total_needed_sheets = math.ceil(quantity / total_per_sheet)
            im_basis = math.ceil(quantity / 20) if total_per_sheet >= 20 else total_needed_sheets
            sticky_basis = math.ceil(quantity / 16) if total_per_sheet >= 16 else total_needed_sheets

            st.success(f"✅ 한 장당 최대 배치 수: {format_result(total_per_sheet)}개")
            st.info(f"📄 기본 수량 기준: {format_result(total_needed_sheets)}장")
            st.write(f"💡 완칼 기준 수량 (아임 기준 20개): {format_result(im_basis)}장")
            st.write(f"💡 완칼 기준 수량 (스티키 기준 16개): {format_result(sticky_basis)}장")
import streamlit as st
import math
import pandas as pd